import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans as FontSans } from "next/font/google";

import { ThemeProvider } from "@/providers/theme-provider";
import OwnerHeader from "@/components/owners/OwnerHeader";

const fontSans = FontSans({
  weight: ["400", "500", "600"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <OwnerHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
